// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// An asset represents a video or an image.
public struct Asset: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name of the asset, in the form of:
  /// `projects/{project}/locations/{location}/assets/{assetId}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The update time.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// User-defined key/value metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Based64-encoded CRC32c checksum of the asset file. For more information,
  /// see the crc32c checksum of the [Cloud Storage Objects
  /// resource](https://cloud.google.com/storage/docs/json_api/v1/objects).
  /// If crc32c is omitted or left empty when the asset is created, this field is
  /// filled by the crc32c checksum of the Cloud Storage object indicated by
  /// [VideoAsset.uri][google.cloud.video.livestream.v1.Asset.VideoAsset.uri] or
  /// [ImageAsset.uri][google.cloud.video.livestream.v1.Asset.ImageAsset.uri]. If
  /// crc32c is set, the asset can't be created if the crc32c value does not
  /// match with the crc32c checksum of the Cloud Storage object indicated by
  /// [VideoAsset.uri][google.cloud.video.livestream.v1.Asset.VideoAsset.uri] or
  /// [ImageAsset.uri][google.cloud.video.livestream.v1.Asset.ImageAsset.uri].
  ///
  /// [google.cloud.video.livestream.v1.Asset.ImageAsset.uri]: <doc:Asset/ImageAsset/uri>
  /// [google.cloud.video.livestream.v1.Asset.VideoAsset.uri]: <doc:Asset/VideoAsset/uri>
  public var crc32C: Swift.String = Swift.String()

  /// Output only. The state of the asset resource.
  public var state: Asset.State = Asset.State()

  /// Output only. Only present when `state` is `ERROR`. The reason for the error
  /// state of the asset.
  public var error: GoogleRpc.Status? = nil

  /// The reference to the asset.
  /// The maximum size of the resource is 250 MB.
  public var resource: OneOf_Resource? = nil

  /// Initialize a new instance of `Asset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Asset().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case video = "video"
    case image = "image"
    case crc32C = "crc32c"
    case state = "state"
    case error = "error"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.crc32C = try container.decode(Swift.String.self, forKey: .crc32C)
    self.state = try container.decode(Asset.State.self, forKey: .state)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)

    var resource: OneOf_Resource? = nil
    let resourceCheckAndSet = {
      if resource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resource'"))
      }
      resource = $0
    }
    if let video = try container.decodeIfPresent(Asset.VideoAsset?.self, forKey: .video) {
      try resourceCheckAndSet(.video(video))
    }
    if let image = try container.decodeIfPresent(Asset.ImageAsset?.self, forKey: .image) {
      try resourceCheckAndSet(.image(image))
    }
    self.resource = resource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.crc32C, forKey: .crc32C)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.error, forKey: .error)

    if let choice = self.resource {
      switch choice {
      case .video(let value):
        try container.encode(value, forKey: .video)
      case .image(let value):
        try container.encode(value, forKey: .image)
      }
    }
  }

  /// VideoAsset represents a video. The supported formats are MP4, MPEG-TS, and
  /// FLV. The supported video codec is H264. The supported audio codecs are
  /// AAC, AC3, MP2, and MP3.
  public struct VideoAsset: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Cloud Storage URI of the video. The format is `gs://my-bucket/my-object`.
    public var uri: Swift.String = Swift.String()

    /// Initialize a new instance of `VideoAsset`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VideoAsset().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Asset.VideoAsset"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Image represents an image. The supported formats are JPEG, PNG.
  public struct ImageAsset: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Cloud Storage URI of the image. The format is `gs://my-bucket/my-object`.
    public var uri: Swift.String = Swift.String()

    /// Initialize a new instance of `ImageAsset`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImageAsset().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Asset.ImageAsset"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// State of the asset resource.
  public enum State: Codable, Equatable, Sendable {
    /// State is not specified.
    case unspecified
    /// The asset is being created.
    case creating
    /// The asset is ready for use.
    case active
    /// The asset is being deleted.
    case deleting
    /// The asset has an error.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .error: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The reference to the asset.
  /// The maximum size of the resource is 250 MB.
  public enum OneOf_Resource: Codable, Equatable, Sendable {
    /// VideoAsset represents a video.
    indirect case video(Asset.VideoAsset?)
    /// ImageAsset represents an image.
    indirect case image(Asset.ImageAsset?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Asset"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
