// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Audio stream resource.
public struct AudioStream: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Specifies whether pass through (transmuxing) is enabled or not.
  /// If set to `true`, the rest of the settings, other than `mapping`, will be
  /// ignored. The default is `false`.
  public var transmux: Swift.Bool = Swift.Bool()

  /// The codec for this audio stream. The default is `aac`.
  ///
  /// Supported audio codecs:
  ///
  /// - `aac`
  public var codec: Swift.String = Swift.String()

  /// Required. Audio bitrate in bits per second. Must be between 1 and
  /// 10,000,000.
  public var bitrateBps: Swift.Int32 = Swift.Int32()

  /// Number of audio channels. Must be between 1 and 6. The default is 2.
  public var channelCount: Swift.Int32 = Swift.Int32()

  /// A list of channel names specifying layout of the audio channels.
  /// This only affects the metadata embedded in the container headers, if
  /// supported by the specified format. The default is `[fl, fr]`.
  ///
  /// Supported channel names:
  ///
  /// - `fl` - Front left channel
  /// - `fr` - Front right channel
  /// - `sl` - Side left channel
  /// - `sr` - Side right channel
  /// - `fc` - Front center channel
  /// - `lfe` - Low frequency
  public var channelLayout: [Swift.String] = []

  /// The mapping for the input streams and audio channels.
  public var mapping: [AudioStream.AudioMapping] = []

  /// The audio sample rate in Hertz. The default is 48000 Hertz.
  public var sampleRateHertz: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AudioStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AudioStream().with { $0.transmux = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let transmux = CodingKeys(stringValue: "transmux")
    static let codec = CodingKeys(stringValue: "codec")
    static let bitrateBps = CodingKeys(stringValue: "bitrateBps")
    static let channelCount = CodingKeys(stringValue: "channelCount")
    static let channelLayout = CodingKeys(stringValue: "channelLayout")
    static let mapping = CodingKeys(stringValue: "mapping")
    static let sampleRateHertz = CodingKeys(stringValue: "sampleRateHertz")

    static let _knownKeys: Set<Swift.String> = [
      "transmux",
      "codec",
      "bitrateBps",
      "channelCount",
      "channelLayout",
      "mapping",
      "sampleRateHertz",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .transmux) {
      self.transmux = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .codec) {
      self.codec = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .bitrateBps) {
      self.bitrateBps = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .channelCount) {
      self.channelCount = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .channelLayout) {
      self.channelLayout = value
    }
    if let value = try container.decodeIfPresent([AudioStream.AudioMapping].self, forKey: .mapping)
    {
      self.mapping = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sampleRateHertz) {
      self.sampleRateHertz = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.transmux, forKey: .transmux)
    try container.encode(self.codec, forKey: .codec)
    try container.encode(self.bitrateBps, forKey: .bitrateBps)
    try container.encode(self.channelCount, forKey: .channelCount)
    try container.encode(self.channelLayout, forKey: .channelLayout)
    try container.encode(self.mapping, forKey: .mapping)
    try container.encode(self.sampleRateHertz, forKey: .sampleRateHertz)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The mapping for the input streams and audio channels.
  public struct AudioMapping: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The `Channel`
    /// [InputAttachment.key][google.cloud.video.livestream.v1.InputAttachment.key]
    /// that identifies the input that this audio mapping applies to. If an
    /// active input doesn't have an audio mapping, the primary audio track in
    /// the input stream will be selected.
    ///
    /// [google.cloud.video.livestream.v1.InputAttachment.key]: <doc:InputAttachment/key>
    public var inputKey: Swift.String = Swift.String()

    /// Required. The zero-based index of the track in the input stream.
    /// All [mapping][google.cloud.video.livestream.v1.AudioStream.mapping]s in
    /// the same [AudioStream][google.cloud.video.livestream.v1.AudioStream] must
    /// have the same input track.
    ///
    /// [google.cloud.video.livestream.v1.AudioStream]: <doc:AudioStream>
    /// [google.cloud.video.livestream.v1.AudioStream.mapping]: <doc:AudioStream/mapping>
    public var inputTrack: Swift.Int32 = Swift.Int32()

    /// Required. The zero-based index of the channel in the input stream.
    public var inputChannel: Swift.Int32 = Swift.Int32()

    /// Required. The zero-based index of the channel in the output audio stream.
    /// Must be consistent with the
    /// [input_channel][google.cloud.video.livestream.v1.AudioStream.AudioMapping.input_channel].
    ///
    /// [google.cloud.video.livestream.v1.AudioStream.AudioMapping.input_channel]: <doc:AudioStream/AudioMapping/inputChannel>
    public var outputChannel: Swift.Int32 = Swift.Int32()

    /// Audio volume control in dB. Negative values decrease volume,
    /// positive values increase. The default is 0.
    public var gainDb: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AudioMapping`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AudioMapping().with { $0.inputKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputKey = CodingKeys(stringValue: "inputKey")
      static let inputTrack = CodingKeys(stringValue: "inputTrack")
      static let inputChannel = CodingKeys(stringValue: "inputChannel")
      static let outputChannel = CodingKeys(stringValue: "outputChannel")
      static let gainDb = CodingKeys(stringValue: "gainDb")

      static let _knownKeys: Set<Swift.String> = [
        "inputKey",
        "inputTrack",
        "inputChannel",
        "outputChannel",
        "gainDb",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputKey) {
        self.inputKey = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .inputTrack) {
        self.inputTrack = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .inputChannel) {
        self.inputChannel = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .outputChannel) {
        self.outputChannel = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .gainDb) {
        self.gainDb = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inputKey, forKey: .inputKey)
      try container.encode(self.inputTrack, forKey: .inputTrack)
      try container.encode(self.inputChannel, forKey: .inputChannel)
      try container.encode(self.outputChannel, forKey: .outputChannel)
      try container.encode(self.gainDb, forKey: .gainDb)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.AudioStream.AudioMapping"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.AudioStream"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
