// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Advanced configurations for auto-generated text streams.
public struct AutoTranscriptionConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether auto-generated text streams are displayed synchronously
  /// or asynchronously with the original audio.
  public var displayTiming: AutoTranscriptionConfig.DisplayTiming =
    AutoTranscriptionConfig.DisplayTiming()

  /// Optional. Tunes the latency and quality of auto-generated captions.
  public var qualityPreset: AutoTranscriptionConfig.QualityPreset =
    AutoTranscriptionConfig.QualityPreset()

  /// Initialize a new instance of `AutoTranscriptionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoTranscriptionConfig().with { $0.displayTiming = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Whether auto-generated text streams are displayed synchronously or
  /// asynchronously with the original audio.
  public enum DisplayTiming: Codable, Equatable, Sendable {
    /// Display timing is not specified. Caption display will be asynchronous by
    /// default.
    case unspecified
    /// Caption will be displayed asynchronous with audio.
    case `async`
    /// Caption will be displayed synchronous with audio. This option increases
    /// overall media output latency, and reduces viewing latency between audio
    /// and auto-generated captions.
    case sync
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`async`: return 1
      case .sync: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISPLAY_TIMING_UNSPECIFIED"
      case .`async`: return "ASYNC"
      case .sync: return "SYNC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DisplayTiming/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISPLAY_TIMING_UNSPECIFIED": self = .unspecified
      case "ASYNC": self = .`async`
      case "SYNC": self = .sync
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DisplayTiming/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`async`
      case 2: self = .sync
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`async`: return try container.encode(1)
      case .sync: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Presets to tune the latency and quality of auto-generated captions.
  public enum QualityPreset: Codable, Equatable, Sendable {
    /// Quality Preset is not specified. By default, BALANCED_QUALITY will be
    /// used.
    case unspecified
    /// Reduce the latency of auto-generated captions. This may reduce the
    /// quality of the captions.
    case lowLatency
    /// Default behavior when QualityPreset is not specified.
    case balancedQuality
    /// Increases the quality of the auto-generated captions at the cost of
    /// higher latency.
    case improvedQuality
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .lowLatency: return 1
      case .balancedQuality: return 2
      case .improvedQuality: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "QUALITY_PRESET_UNSPECIFIED"
      case .lowLatency: return "LOW_LATENCY"
      case .balancedQuality: return "BALANCED_QUALITY"
      case .improvedQuality: return "IMPROVED_QUALITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:QualityPreset/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "QUALITY_PRESET_UNSPECIFIED": self = .unspecified
      case "LOW_LATENCY": self = .lowLatency
      case "BALANCED_QUALITY": self = .balancedQuality
      case "IMPROVED_QUALITY": self = .improvedQuality
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:QualityPreset/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .lowLatency
      case 2: self = .balancedQuality
      case 3: self = .improvedQuality
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .lowLatency: return try container.encode(1)
      case .balancedQuality: return try container.encode(2)
      case .improvedQuality: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.AutoTranscriptionConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
