// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Channel resource represents the processor that does a user-defined
/// "streaming" operation, which includes getting an input stream through an
/// input, transcoding it to multiple renditions, and publishing output live
/// streams in certain formats (for example, HLS or DASH) to the specified
/// location.
public struct Channel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the channel, in the form of:
  /// `projects/{project}/locations/{location}/channels/{channelId}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The update time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// User-defined key/value metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A list of input attachments that this channel uses.
  /// One channel can have multiple inputs as the input sources. Only one
  /// input can be selected as the input source at one time.
  public var inputAttachments: [InputAttachment] = []

  /// Output only. The
  /// [InputAttachment.key][google.cloud.video.livestream.v1.InputAttachment.key]
  /// that serves as the current input source. The first input in the
  /// [input_attachments][google.cloud.video.livestream.v1.Channel.input_attachments]
  /// is the initial input source.
  ///
  /// [google.cloud.video.livestream.v1.Channel.input_attachments]: <doc:Channel/inputAttachments>
  /// [google.cloud.video.livestream.v1.InputAttachment.key]: <doc:InputAttachment/key>
  public var activeInput: Swift.String = Swift.String()

  /// Required. Information about the output (that is, the Cloud Storage bucket
  /// to store the generated live stream).
  public var output: Channel.Output? = nil

  /// List of elementary streams.
  public var elementaryStreams: [ElementaryStream] = []

  /// List of multiplexing settings for output streams.
  public var muxStreams: [MuxStream] = []

  /// List of output manifests.
  public var manifests: [Manifest] = []

  /// Optional. List of multiplexing settings of streams for distributions.
  public var distributionStreams: [DistributionStream] = []

  /// Optional. List of distributions.
  public var distributions: [Distribution] = []

  /// List of output sprite sheets.
  public var spriteSheets: [SpriteSheet] = []

  /// Output only. State of the streaming operation.
  public var streamingState: Channel.StreamingState = Channel.StreamingState()

  /// Output only. A description of the reason for the streaming error. This
  /// property is always present when
  /// [streaming_state][google.cloud.video.livestream.v1.Channel.streaming_state]
  /// is
  /// [STREAMING_ERROR][google.cloud.video.livestream.v1.Channel.StreamingState.STREAMING_ERROR].
  ///
  /// [google.cloud.video.livestream.v1.Channel.StreamingState.STREAMING_ERROR]: <doc:Channel/StreamingState/streamingError>
  /// [google.cloud.video.livestream.v1.Channel.streaming_state]: <doc:Channel/streamingState>
  public var streamingError: GoogleRpc.Status? = nil

  /// Configuration of platform logs for this channel.
  public var logConfig: LogConfig? = nil

  /// Configuration of timecode for this channel.
  public var timecodeConfig: TimecodeConfig? = nil

  /// Optional. Encryption configurations for this channel. Each configuration
  /// has an ID which is referred to by each MuxStream to indicate which
  /// configuration is used for that output.
  public var encryptions: [Encryption] = []

  /// The configuration for input sources defined in
  /// [input_attachments][google.cloud.video.livestream.v1.Channel.input_attachments].
  ///
  /// [google.cloud.video.livestream.v1.Channel.input_attachments]: <doc:Channel/inputAttachments>
  public var inputConfig: InputConfig? = nil

  /// Optional. Configuration for retention of output files for this channel.
  public var retentionConfig: RetentionConfig? = nil

  /// Optional. List of static overlay images. Those images display over the
  /// output content for the whole duration of the live stream.
  public var staticOverlays: [StaticOverlay] = []

  /// Optional. Advanced configurations for auto-generated text streams.
  public var autoTranscriptionConfig: AutoTranscriptionConfig? = nil

  /// Initialize a new instance of `Channel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Channel().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Location of output file(s) in a Google Cloud Storage bucket.
  public struct Output: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// URI for the output file(s). For example, `gs://my-bucket/outputs/`.
    public var uri: Swift.String = Swift.String()

    /// Initialize a new instance of `Output`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Output().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Channel.Output"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// State of streaming operation that the channel is running.
  public enum StreamingState: Codable, Equatable, Sendable {
    /// Streaming state is not specified.
    case unspecified
    /// Channel is getting the input stream, generating the live streams to the
    /// specified output location.
    case streaming
    /// Channel is waiting for the input stream through the input.
    case awaitingInput
    /// Channel is running, but has trouble publishing the live streams onto the
    /// specified output location (for example, the specified Cloud Storage
    /// bucket is not writable).
    case streamingError
    /// Channel is generating live streams with no input stream. Live streams are
    /// filled out with black screen, while input stream is missing.
    /// Not supported yet.
    case streamingNoInput
    /// Channel is stopped, finishing live streams.
    case stopped
    /// Channel is starting.
    case starting
    /// Channel is stopping.
    case stopping
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .streaming: return 1
      case .awaitingInput: return 2
      case .streamingError: return 4
      case .streamingNoInput: return 5
      case .stopped: return 6
      case .starting: return 7
      case .stopping: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STREAMING_STATE_UNSPECIFIED"
      case .streaming: return "STREAMING"
      case .awaitingInput: return "AWAITING_INPUT"
      case .streamingError: return "STREAMING_ERROR"
      case .streamingNoInput: return "STREAMING_NO_INPUT"
      case .stopped: return "STOPPED"
      case .starting: return "STARTING"
      case .stopping: return "STOPPING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StreamingState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STREAMING_STATE_UNSPECIFIED": self = .unspecified
      case "STREAMING": self = .streaming
      case "AWAITING_INPUT": self = .awaitingInput
      case "STREAMING_ERROR": self = .streamingError
      case "STREAMING_NO_INPUT": self = .streamingNoInput
      case "STOPPED": self = .stopped
      case "STARTING": self = .starting
      case "STOPPING": self = .stopping
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StreamingState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .streaming
      case 2: self = .awaitingInput
      case 4: self = .streamingError
      case 5: self = .streamingNoInput
      case 6: self = .stopped
      case 7: self = .starting
      case 8: self = .stopping
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .streaming: return try container.encode(1)
      case .awaitingInput: return try container.encode(2)
      case .streamingError: return try container.encode(4)
      case .streamingNoInput: return try container.encode(5)
      case .stopped: return try container.encode(6)
      case .starting: return try container.encode(7)
      case .stopping: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Channel"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
