// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Clip is a sub-resource under channel. Each clip represents a clipping
/// operation that generates a VOD playlist from its channel given a set of
/// timestamp ranges.
public struct Clip: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the clip, in the following format:
  /// `projects/{project}/locations/{location}/channels/{channelId}/clips/{clipId}`.
  /// `{clipId}` is a user-specified resource id that conforms to the following
  /// criteria:
  ///
  /// 1. 1 character minimum, 63 characters maximum
  /// 2. Only contains letters, digits, underscores, and hyphens
  public var name: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the clip resource.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the clip request starts to be processed.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The update timestamp of the clip resource.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// The labels associated with this resource. Each label is a key-value pair.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The state of the clip.
  public var state: Clip.State = Clip.State()

  /// Specify the `output_uri` to determine where to place the clip segments and
  /// clip manifest files in Cloud Storage. The manifests specified in
  /// `clip_manifests` fields will be placed under this URI. The exact URI of the
  /// generated manifests will be provided in `clip_manifests.output_uri` for
  /// each manifest.
  /// Example:
  /// "output_uri": "gs://my-bucket/clip-outputs"
  /// "clip_manifests.output_uri": "gs://my-bucket/clip-outputs/main.m3u8"
  public var outputUri: Swift.String = Swift.String()

  /// Output only. An error object that describes the reason for the failure.
  /// This property only presents when `state` is `FAILED`.
  public var error: GoogleRpc.Status? = nil

  /// The specified ranges of segments to generate a clip.
  public var slices: [Clip.Slice] = []

  /// Required. A list of clip manifests. Currently only one clip manifest is
  /// allowed.
  public var clipManifests: [Clip.ClipManifest] = []

  /// Optional. OutputType of the clip. If not specified, the default value is
  /// MANIFEST.
  public var outputType: Clip.OutputType = Clip.OutputType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Clip`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Clip().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let outputUri = CodingKeys(stringValue: "outputUri")
    static let error = CodingKeys(stringValue: "error")
    static let slices = CodingKeys(stringValue: "slices")
    static let clipManifests = CodingKeys(stringValue: "clipManifests")
    static let outputType = CodingKeys(stringValue: "outputType")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "startTime",
      "updateTime",
      "labels",
      "state",
      "outputUri",
      "error",
      "slices",
      "clipManifests",
      "outputType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Clip.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUri) {
      self.outputUri = value
    }
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    if let value = try container.decodeIfPresent([Clip.Slice].self, forKey: .slices) {
      self.slices = value
    }
    if let value = try container.decodeIfPresent([Clip.ClipManifest].self, forKey: .clipManifests) {
      self.clipManifests = value
    }
    if let value = try container.decodeIfPresent(Clip.OutputType.self, forKey: .outputType) {
      self.outputType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.outputUri, forKey: .outputUri)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encode(self.slices, forKey: .slices)
    try container.encode(self.clipManifests, forKey: .clipManifests)
    try container.encode(self.outputType, forKey: .outputType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// TimeSlice represents a tuple of Unix epoch timestamps that specifies a time
  /// range.
  public struct TimeSlice: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The mark-in Unix epoch time in the original live stream manifest.
    public var markinTime: GoogleWKT.WKTTimestamp? = nil

    /// The mark-out Unix epoch time in the original live stream manifest.
    public var markoutTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TimeSlice`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeSlice().with { $0.markinTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let markinTime = CodingKeys(stringValue: "markinTime")
      static let markoutTime = CodingKeys(stringValue: "markoutTime")

      static let _knownKeys: Set<Swift.String> = [
        "markinTime",
        "markoutTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.markinTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .markinTime)
      self.markoutTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .markoutTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.markinTime, forKey: .markinTime)
      try container.encodeIfPresent(self.markoutTime, forKey: .markoutTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Clip.TimeSlice"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Slice represents a slice of the requested clip.
  public struct Slice: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The allowlist forms of a slice.
    public var kind: OneOf_Kind? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Slice`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Slice().with { $0.timeSlice = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let timeSlice = CodingKeys(stringValue: "timeSlice")

      static let _knownKeys: Set<Swift.String> = [
        "timeSlice"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let timeSlice = try container.decodeIfPresent(Clip.TimeSlice?.self, forKey: .timeSlice) {
        try kindCheckAndSet(.timeSlice(timeSlice))
      }
      self.kind = kind
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .timeSlice(let value):
          try container.encode(value, forKey: .timeSlice)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The allowlist forms of a slice.
    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// A slice in form of a tuple of Unix epoch time.
      indirect case timeSlice(Clip.TimeSlice?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Clip.Slice"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// ClipManifest identifies a source manifest for the generated clip manifest.
  public struct ClipManifest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. A unique key that identifies a manifest config in the parent
    /// channel. This key is the same as `channel.manifests.key` for the selected
    /// manifest.
    public var manifestKey: Swift.String = Swift.String()

    /// Output only. The output URI of the generated clip manifest. This field
    /// will be populated when the CreateClip request is accepted. Current output
    /// format is provided below but may change in the future. Please read this
    /// field to get the uri to the generated clip manifest. Format:
    /// {clip.output_uri}/{channel.manifest.fileName} Example:
    /// gs://my-bucket/clip-outputs/main.m3u8
    public var outputUri: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ClipManifest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClipManifest().with { $0.manifestKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let manifestKey = CodingKeys(stringValue: "manifestKey")
      static let outputUri = CodingKeys(stringValue: "outputUri")

      static let _knownKeys: Set<Swift.String> = [
        "manifestKey",
        "outputUri",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .manifestKey) {
        self.manifestKey = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUri) {
        self.outputUri = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.manifestKey, forKey: .manifestKey)
      try container.encode(self.outputUri, forKey: .outputUri)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Clip.ClipManifest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// State of clipping operation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// State is not specified.
    case unspecified
    /// The operation is pending to be picked up by the server.
    case pending
    /// The server admitted this create clip request, and
    /// outputs are under processing.
    case creating
    /// Outputs are available in the specified Cloud Storage bucket. For
    /// additional information, see the `outputs` field.
    case succeeded
    /// The operation has failed. For additional information, see the `error`
    /// field.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .creating: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .creating: return "CREATING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "CREATING": self = .creating
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .creating
      case 3: self = .succeeded
      case 4: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .pending: return try container.encode("PENDING")
      case .creating: return try container.encode("CREATING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// OutputType represents the output type of the clip.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum OutputType: Codable, Equatable, Sendable {
    /// OutputType is not specified.
    case unspecified
    /// OutputType is a VOD manifest. This is the default value.
    case manifest
    /// OutputType is an MP4 file.
    case mp4
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .manifest: return 1
      case .mp4: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OUTPUT_TYPE_UNSPECIFIED"
      case .manifest: return "MANIFEST"
      case .mp4: return "MP4"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OutputType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OUTPUT_TYPE_UNSPECIFIED": self = .unspecified
      case "MANIFEST": self = .manifest
      case "MP4": self = .mp4
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OutputType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .manifest
      case 2: self = .mp4
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OUTPUT_TYPE_UNSPECIFIED")
      case .manifest: return try container.encode("MANIFEST")
      case .mp4: return try container.encode("MP4")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Clip"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
