// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Multiplexing settings for output streams used in
/// [Distribution][google.cloud.video.livestream.v1.Distribution].
///
/// [google.cloud.video.livestream.v1.Distribution]: <doc:Distribution>
public struct DistributionStream: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. A unique key for this distribution stream. The key must be 1-63
  /// characters in length. The key must begin and end with a letter (regardless
  /// of case) or a number, but can contain dashes or underscores in between.
  public var key: Swift.String = Swift.String()

  /// Required. The container format.
  ///
  /// Supported container formats:
  ///
  /// - `ts`, must contain exactly one audio stream and up to one video stream.
  /// - `flv`, must contain at most one audio stream and at most one video
  /// stream.
  public var container: Swift.String = Swift.String()

  /// Required. List of `ElementaryStream`
  /// [key][google.cloud.video.livestream.v1.ElementaryStream.key]s multiplexed
  /// in this stream. Must contain at least one audio stream and up to one video
  /// stream.
  ///
  /// [google.cloud.video.livestream.v1.ElementaryStream.key]: <doc:ElementaryStream/key>
  public var elementaryStreams: [Swift.String] = []

  /// Initialize a new instance of `DistributionStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DistributionStream().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.DistributionStream"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
