// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Distribution configuration.
public struct Distribution: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. A unique key for this distribution. The key must be 1-63
  /// characters in length. The key must begin and end with a letter (regardless
  /// of case) or a number, but can contain dashes or underscores in between.
  public var key: Swift.String = Swift.String()

  /// Required. `DistributionStream`
  /// [key][google.cloud.video.livestream.v1.DistributionStream.key]s that should
  /// appear in this distribution output.
  ///
  /// - For SRT protocol, only `ts` distribution streams can be specified.
  /// - For RTMP protocol, only `flv` distribution streams can be specified.
  ///
  /// [google.cloud.video.livestream.v1.DistributionStream.key]: <doc:DistributionStream/key>
  public var distributionStream: Swift.String = Swift.String()

  /// Output only. State of the distribution.
  public var state: Distribution.State = Distribution.State()

  /// Output only. Only present when the `state` is `ERROR`. The reason for the
  /// error state of the distribution.
  public var error: GoogleRpc.Status? = nil

  /// Configurations for the output endpoint by streaming protocols.
  public var endpoint: OneOf_Endpoint? = nil

  /// Initialize a new instance of `Distribution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Distribution().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case key = "key"
    case distributionStream = "distributionStream"
    case state = "state"
    case error = "error"
    case srtPush = "srtPush"
    case rtmpPush = "rtmpPush"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.key = try container.decode(Swift.String.self, forKey: .key)
    self.distributionStream = try container.decode(Swift.String.self, forKey: .distributionStream)
    self.state = try container.decode(Distribution.State.self, forKey: .state)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)

    var endpoint: OneOf_Endpoint? = nil
    let endpointCheckAndSet = {
      if endpoint != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'endpoint'"))
      }
      endpoint = $0
    }
    if let srtPush = try container.decodeIfPresent(SrtPushOutputEndpoint?.self, forKey: .srtPush) {
      try endpointCheckAndSet(.srtPush(srtPush))
    }
    if let rtmpPush = try container.decodeIfPresent(RtmpPushOutputEndpoint?.self, forKey: .rtmpPush)
    {
      try endpointCheckAndSet(.rtmpPush(rtmpPush))
    }
    self.endpoint = endpoint
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.distributionStream, forKey: .distributionStream)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.error, forKey: .error)

    if let choice = self.endpoint {
      switch choice {
      case .srtPush(let value):
        try container.encode(value, forKey: .srtPush)
      case .rtmpPush(let value):
        try container.encode(value, forKey: .rtmpPush)
      }
    }
  }

  /// State of this distribution.
  public enum State: Codable, Equatable, Sendable {
    /// State is not specified.
    case unspecified
    /// Distribution has trouble to produce or deliver the output.
    case error
    /// Distribution is not ready to be started.
    case notReady
    /// Distribution is ready to be started.
    case ready
    /// Distribution is already started and is waiting for input.
    case awaitingInput
    /// Distribution is already started and is generating output.
    case distributing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .error: return 5
      case .notReady: return 6
      case .ready: return 7
      case .awaitingInput: return 8
      case .distributing: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .error: return "ERROR"
      case .notReady: return "NOT_READY"
      case .ready: return "READY"
      case .awaitingInput: return "AWAITING_INPUT"
      case .distributing: return "DISTRIBUTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ERROR": self = .error
      case "NOT_READY": self = .notReady
      case "READY": self = .ready
      case "AWAITING_INPUT": self = .awaitingInput
      case "DISTRIBUTING": self = .distributing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 5: self = .error
      case 6: self = .notReady
      case 7: self = .ready
      case 8: self = .awaitingInput
      case 9: self = .distributing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .error: return try container.encode(5)
      case .notReady: return try container.encode(6)
      case .ready: return try container.encode(7)
      case .awaitingInput: return try container.encode(8)
      case .distributing: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Configurations for the output endpoint by streaming protocols.
  public enum OneOf_Endpoint: Codable, Equatable, Sendable {
    /// Output endpoint using SRT_PUSH.
    indirect case srtPush(SrtPushOutputEndpoint?)
    /// Output endpoint using RTMP_PUSH.
    indirect case rtmpPush(RtmpPushOutputEndpoint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Distribution"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
