// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// DvrSession is a sub-resource under channel. Each DvrSession represents a DVR
/// recording of the live stream for a specific time range.
public struct DvrSession: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the DVR session, in the following format:
  /// `projects/{project}/locations/{location}/channels/{channelId}/dvrSessions/{dvrSessionId}`.
  /// `{dvrSessionId}` is a user-specified resource id that conforms to the
  /// following criteria:
  ///
  /// 1. 1 character minimum, 63 characters maximum
  /// 2. Only contains letters, digits, underscores, and hyphens
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The update time.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. User-defined key/value metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The state of the clip.
  public var state: DvrSession.State = DvrSession.State()

  /// Output only. An error object that describes the reason for the failure.
  /// This property only presents when `state` is `FAILED`.
  public var error: GoogleRpc.Status? = nil

  /// Required. A list of DVR manifests. Currently only one DVR manifest is
  /// allowed.
  public var dvrManifests: [DvrSession.DvrManifest] = []

  /// Required. The specified ranges of segments to generate a DVR recording.
  public var dvrWindows: [DvrSession.DvrWindow] = []

  /// Initialize a new instance of `DvrSession`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DvrSession().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// DvrManifest identifies a source manifest and specifies a file name for the
  /// generated DVR manifest.
  public struct DvrManifest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. A unique key that identifies a manifest config in the parent
    /// channel. This key is the same as `channel.manifests.key` for the selected
    /// manifest.
    public var manifestKey: Swift.String = Swift.String()

    /// Output only. The output URI of the DVR manifest. The DVR output will be
    /// placed in a directory named `dvr/dvrSessionId/` under the parent
    /// channel's output uri. Format:
    /// {channel.output.uri}/dvr/{dvrSessionId}/{channel.manifests.fileName}
    /// Example: gs://my-bucket/outputs/dvr/my-dvr-session/main.m3u8
    public var outputUri: Swift.String = Swift.String()

    /// Initialize a new instance of `DvrManifest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DvrManifest().with { $0.manifestKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.DvrSession.DvrManifest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// DvrWindow represents a DVR window.
  public struct DvrWindow: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The allowlist forms of a DVR window.
    public var kind: OneOf_Kind? = nil

    /// Initialize a new instance of `DvrWindow`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DvrWindow().with { $0.timeInterval = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case timeInterval = "timeInterval"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let timeInterval = try container.decodeIfPresent(TimeInterval?.self, forKey: .timeInterval)
      {
        try kindCheckAndSet(.timeInterval(timeInterval))
      }
      self.kind = kind
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .timeInterval(let value):
          try container.encode(value, forKey: .timeInterval)
        }
      }
    }

    /// The allowlist forms of a DVR window.
    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// A time interval in the form of a tuple of Unix epoch time.
      indirect case timeInterval(TimeInterval?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.DvrSession.DvrWindow"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// State of the DVR session.
  public enum State: Codable, Equatable, Sendable {
    /// State is not specified.
    case unspecified
    /// The operation is pending to be picked up by the server.
    case pending
    /// The session is being updated.
    case updating
    /// The session is scheduled and waiting for the start time.
    case scheduled
    /// The session is currently in progress and the outputs are available in the
    /// specified Cloud Storage bucket. For additional information, see the
    /// `dvr_manifests.output_uri` field.
    case live
    /// Outputs are available in the specified Cloud Storage bucket. For
    /// additional information, see the `dvr_manifests.output_uri` field.
    case finished
    /// The operation has failed. For additional information, see the `error`
    /// field.
    case failed
    /// The session is being deleted.
    case deleting
    /// The session is being post processed.
    case postProcessing
    /// The session is in cooldown. The cooldown period lasts for 60 seconds.
    /// When the DVR session is updated by the user to have a new end time that
    /// is likely already in the past, the DVR manifest will end as soon as
    /// possible and the DVR session will move to this state. This is done to
    /// prevent the players to receive a manifest update that removes a segment
    /// that has already been played. After the cooldown period ends, a new
    /// manifest is generated that honors the new end time.
    case cooldown
    /// The session is being stopped. The session will move to STOPPING state, if
    /// the parent channel is updated.
    case stopping
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .updating: return 2
      case .scheduled: return 3
      case .live: return 4
      case .finished: return 5
      case .failed: return 6
      case .deleting: return 7
      case .postProcessing: return 8
      case .cooldown: return 9
      case .stopping: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .updating: return "UPDATING"
      case .scheduled: return "SCHEDULED"
      case .live: return "LIVE"
      case .finished: return "FINISHED"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .postProcessing: return "POST_PROCESSING"
      case .cooldown: return "COOLDOWN"
      case .stopping: return "STOPPING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "UPDATING": self = .updating
      case "SCHEDULED": self = .scheduled
      case "LIVE": self = .live
      case "FINISHED": self = .finished
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      case "POST_PROCESSING": self = .postProcessing
      case "COOLDOWN": self = .cooldown
      case "STOPPING": self = .stopping
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .updating
      case 3: self = .scheduled
      case 4: self = .live
      case 5: self = .finished
      case 6: self = .failed
      case 7: self = .deleting
      case 8: self = .postProcessing
      case 9: self = .cooldown
      case 10: self = .stopping
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .updating: return try container.encode(2)
      case .scheduled: return try container.encode(3)
      case .live: return try container.encode(4)
      case .finished: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .deleting: return try container.encode(7)
      case .postProcessing: return try container.encode(8)
      case .cooldown: return try container.encode(9)
      case .stopping: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.DvrSession"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
