// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Encryption setting when updating encryption.
public struct EncryptionUpdate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Identifier for the encryption option to be updated.
  public var id: Swift.String = Swift.String()

  /// Defines where new content keys are stored.
  public var secretSource: OneOf_SecretSource? = nil

  /// Initialize a new instance of `EncryptionUpdate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EncryptionUpdate().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case id = "id"
    case secretManagerKeySource = "secretManagerKeySource"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)

    var secretSource: OneOf_SecretSource? = nil
    let secretSourceCheckAndSet = {
      if secretSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'secretSource'"))
      }
      secretSource = $0
    }
    if let secretManagerKeySource = try container.decodeIfPresent(
      Encryption.SecretManagerSource?.self, forKey: .secretManagerKeySource)
    {
      try secretSourceCheckAndSet(.secretManagerKeySource(secretManagerKeySource))
    }
    self.secretSource = secretSource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)

    if let choice = self.secretSource {
      switch choice {
      case .secretManagerKeySource(let value):
        try container.encode(value, forKey: .secretManagerKeySource)
      }
    }
  }

  /// Defines where new content keys are stored.
  public enum OneOf_SecretSource: Codable, Equatable, Sendable {
    /// For keys stored in Google Secret Manager.
    indirect case secretManagerKeySource(Encryption.SecretManagerSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.EncryptionUpdate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
