// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// Event is a sub-resource of a channel, which can be scheduled by the user to
/// execute operations on a channel resource without having to stop the channel.
public struct Event: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the event, in the form of:
  /// `projects/{project}/locations/{location}/channels/{channelId}/events/{eventId}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The update time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// User-defined key/value metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// When this field is set to true, the event will be executed at the earliest
  /// time that the server can schedule the event and
  /// [execution_time][google.cloud.video.livestream.v1.Event.execution_time]
  /// will be populated with the time that the server actually schedules the
  /// event.
  ///
  /// [google.cloud.video.livestream.v1.Event.execution_time]: <doc:Event/executionTime>
  public var executeNow: Swift.Bool = Swift.Bool()

  /// The time to execute the event. If you set
  /// [execute_now][google.cloud.video.livestream.v1.Event.execute_now] to
  /// `true`, then do not set this field in the `CreateEvent` request. In
  /// this case, the server schedules the event and populates this field. If you
  /// set [execute_now][google.cloud.video.livestream.v1.Event.execute_now] to
  /// `false`, then you must set this field to at least 10 seconds in the future
  /// or else the event can't be created.
  ///
  /// [google.cloud.video.livestream.v1.Event.execute_now]: <doc:Event/executeNow>
  public var executionTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The state of the event.
  public var state: Event.State = Event.State()

  /// Output only. An error object that describes the reason for the failure.
  /// This property is always present when `state` is `FAILED`.
  public var error: GoogleRpc.Status? = nil

  /// Required. Operation to be executed by this event.
  public var task: OneOf_Task? = nil

  /// Initialize a new instance of `Event`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Event().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case inputSwitch = "inputSwitch"
    case adBreak = "adBreak"
    case returnToProgram = "returnToProgram"
    case slate = "slate"
    case mute = "mute"
    case unmute = "unmute"
    case updateEncryptions = "updateEncryptions"
    case executeNow = "executeNow"
    case executionTime = "executionTime"
    case state = "state"
    case error = "error"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.executeNow = try container.decode(Swift.Bool.self, forKey: .executeNow)
    self.executionTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .executionTime)
    self.state = try container.decode(Event.State.self, forKey: .state)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)

    var task: OneOf_Task? = nil
    let taskCheckAndSet = {
      if task != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'task'"
          ))
      }
      task = $0
    }
    if let inputSwitch = try container.decodeIfPresent(
      Event.InputSwitchTask?.self, forKey: .inputSwitch)
    {
      try taskCheckAndSet(.inputSwitch(inputSwitch))
    }
    if let adBreak = try container.decodeIfPresent(Event.AdBreakTask?.self, forKey: .adBreak) {
      try taskCheckAndSet(.adBreak(adBreak))
    }
    if let returnToProgram = try container.decodeIfPresent(
      Event.ReturnToProgramTask?.self, forKey: .returnToProgram)
    {
      try taskCheckAndSet(.returnToProgram(returnToProgram))
    }
    if let slate = try container.decodeIfPresent(Event.SlateTask?.self, forKey: .slate) {
      try taskCheckAndSet(.slate(slate))
    }
    if let mute = try container.decodeIfPresent(Event.MuteTask?.self, forKey: .mute) {
      try taskCheckAndSet(.mute(mute))
    }
    if let unmute = try container.decodeIfPresent(Event.UnmuteTask?.self, forKey: .unmute) {
      try taskCheckAndSet(.unmute(unmute))
    }
    if let updateEncryptions = try container.decodeIfPresent(
      Event.UpdateEncryptionsTask?.self, forKey: .updateEncryptions)
    {
      try taskCheckAndSet(.updateEncryptions(updateEncryptions))
    }
    self.task = task
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.executeNow, forKey: .executeNow)
    try container.encode(self.executionTime, forKey: .executionTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.error, forKey: .error)

    if let choice = self.task {
      switch choice {
      case .inputSwitch(let value):
        try container.encode(value, forKey: .inputSwitch)
      case .adBreak(let value):
        try container.encode(value, forKey: .adBreak)
      case .returnToProgram(let value):
        try container.encode(value, forKey: .returnToProgram)
      case .slate(let value):
        try container.encode(value, forKey: .slate)
      case .mute(let value):
        try container.encode(value, forKey: .mute)
      case .unmute(let value):
        try container.encode(value, forKey: .unmute)
      case .updateEncryptions(let value):
        try container.encode(value, forKey: .updateEncryptions)
      }
    }
  }

  /// Switches to another input stream. Automatic failover is then disabled.
  public struct InputSwitchTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The
    /// [InputAttachment.key][google.cloud.video.livestream.v1.InputAttachment.key]
    /// of the input to switch to.
    ///
    /// [google.cloud.video.livestream.v1.InputAttachment.key]: <doc:InputAttachment/key>
    public var inputKey: Swift.String = Swift.String()

    /// Initialize a new instance of `InputSwitchTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InputSwitchTask().with { $0.inputKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.InputSwitchTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Inserts a new ad opportunity.
  public struct AdBreakTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Duration of an ad opportunity. Must be greater than 0.
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `AdBreakTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AdBreakTask().with { $0.duration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.AdBreakTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Inserts a slate.
  public struct SlateTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Duration of the slate. Must be greater than 0 if specified.
    /// Omit this field for a long running slate.
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Slate asset to use for the duration. If its duration is less than the
    /// duration of the SlateTask, then the slate loops. The slate must be
    /// represented in the form of:
    /// `projects/{project}/locations/{location}/assets/{assetId}`.
    public var asset: Swift.String = Swift.String()

    /// Initialize a new instance of `SlateTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlateTask().with { $0.duration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.SlateTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Stops any events which are currently running. This only applies to events
  /// with a duration.
  public struct ReturnToProgramTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `ReturnToProgramTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReturnToProgramTask().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.ReturnToProgramTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Mutes the stream.
  public struct MuteTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Duration for which the stream should be muted. If omitted, the stream
    /// will be muted until an UnmuteTask event is sent.
    public var duration: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `MuteTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MuteTask().with { $0.duration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.MuteTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Unmutes the stream. The task fails if the stream is not currently muted.
  public struct UnmuteTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `UnmuteTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UnmuteTask().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.UnmuteTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Update encryption settings.
  public struct UpdateEncryptionsTask: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. A list of
    /// [EncryptionUpdate][google.cloud.video.livestream.v1.EncryptionUpdate]s
    /// that updates the existing encryption settings.
    ///
    /// [google.cloud.video.livestream.v1.EncryptionUpdate]: <doc:EncryptionUpdate>
    public var encryptions: [EncryptionUpdate] = []

    /// Initialize a new instance of `UpdateEncryptionsTask`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpdateEncryptionsTask().with { $0.encryptions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Event.UpdateEncryptionsTask"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// State of the event
  public enum State: Codable, Equatable, Sendable {
    /// Event state is not specified.
    case unspecified
    /// Event is scheduled but not executed yet.
    case scheduled
    /// Event is being executed.
    case running
    /// Event has been successfully executed.
    case succeeded
    /// Event fails to be executed.
    case failed
    /// Event has been created but not scheduled yet.
    case pending
    /// Event was stopped before running for its full duration.
    case stopped
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .running: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .pending: return 5
      case .stopped: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .pending: return "PENDING"
      case .stopped: return "STOPPED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "PENDING": self = .pending
      case "STOPPED": self = .stopped
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 2: self = .running
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .pending
      case 6: self = .stopped
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .scheduled: return try container.encode(1)
      case .running: return try container.encode(2)
      case .succeeded: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .pending: return try container.encode(5)
      case .stopped: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Required. Operation to be executed by this event.
  public enum OneOf_Task: Codable, Equatable, Sendable {
    /// Switches to another input stream.
    indirect case inputSwitch(Event.InputSwitchTask?)
    /// Inserts a new ad opportunity.
    indirect case adBreak(Event.AdBreakTask?)
    /// Stops any running ad break.
    indirect case returnToProgram(Event.ReturnToProgramTask?)
    /// Inserts a slate.
    indirect case slate(Event.SlateTask?)
    /// Mutes the stream.
    indirect case mute(Event.MuteTask?)
    /// Unmutes the stream.
    indirect case unmute(Event.UnmuteTask?)
    /// Updates encryption settings.
    indirect case updateEncryptions(Event.UpdateEncryptionsTask?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Event"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
