// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A group of information for attaching an input resource to this channel.
public struct InputAttachment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique key for this input attachment. The key must be 1-63
  /// characters in length. The key must begin and end with a letter (regardless
  /// of case) or a number, but can contain dashes or underscores in between.
  public var key: Swift.String = Swift.String()

  /// The resource name of an existing input, in the form of:
  /// `projects/{project}/locations/{location}/inputs/{inputId}`.
  public var input: Swift.String = Swift.String()

  /// Automatic failover configurations.
  public var automaticFailover: InputAttachment.AutomaticFailover? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InputAttachment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InputAttachment().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let input = CodingKeys(stringValue: "input")
    static let automaticFailover = CodingKeys(stringValue: "automaticFailover")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "input",
      "automaticFailover",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .input) {
      self.input = value
    }
    self.automaticFailover = try container.decodeIfPresent(
      InputAttachment.AutomaticFailover.self, forKey: .automaticFailover)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.input, forKey: .input)
    try container.encodeIfPresent(self.automaticFailover, forKey: .automaticFailover)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configurations to follow when automatic failover happens.
  public struct AutomaticFailover: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The
    /// [InputAttachment.key][google.cloud.video.livestream.v1.InputAttachment.key]s
    /// of inputs to failover to when this input is disconnected. Currently, only
    /// up to one backup input is supported.
    ///
    /// [google.cloud.video.livestream.v1.InputAttachment.key]: <doc:InputAttachment/key>
    public var inputKeys: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AutomaticFailover`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AutomaticFailover().with { $0.inputKeys = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputKeys = CodingKeys(stringValue: "inputKeys")

      static let _knownKeys: Set<Swift.String> = [
        "inputKeys"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .inputKeys) {
        self.inputKeys = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inputKeys, forKey: .inputKeys)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.video.livestream.v1.InputAttachment.AutomaticFailover"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.InputAttachment"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
