// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Input resource represents the endpoint from which the channel ingests
/// the input stream.
public struct Input: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the input, in the form of:
  /// `projects/{project}/locations/{location}/inputs/{inputId}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The update time.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// User-defined key/value metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Source type.
  public var type: Input.Type_ = Input.Type_()

  /// Tier defines the maximum input specification that is accepted by the
  /// video pipeline. The billing is charged based on the tier specified here.
  /// See [Pricing](https://cloud.google.com/livestream/pricing) for more detail.
  /// The default is `HD`.
  public var tier: Input.Tier = Input.Tier()

  /// Output only. URI to push the input stream to.
  /// Its format depends on the input
  /// [type][google.cloud.video.livestream.v1.Input.type], for example:
  ///
  /// *  `RTMP_PUSH`: `rtmp://1.2.3.4/live/{STREAM-ID}`
  /// *  `SRT_PUSH`: `srt://1.2.3.4:4201?streamid={STREAM-ID}`
  ///
  /// [google.cloud.video.livestream.v1.Input.type]: <doc:Input/type>
  public var uri: Swift.String = Swift.String()

  /// Preprocessing configurations.
  public var preprocessingConfig: PreprocessingConfig? = nil

  /// Security rule for access control.
  public var securityRules: Input.SecurityRule? = nil

  /// Output only. The information for the input stream. This field will be
  /// present only when this input receives the input stream.
  public var inputStreamProperty: InputStreamProperty? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Input`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Input().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let type = CodingKeys(stringValue: "type")
    static let tier = CodingKeys(stringValue: "tier")
    static let uri = CodingKeys(stringValue: "uri")
    static let preprocessingConfig = CodingKeys(stringValue: "preprocessingConfig")
    static let securityRules = CodingKeys(stringValue: "securityRules")
    static let inputStreamProperty = CodingKeys(stringValue: "inputStreamProperty")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "type",
      "tier",
      "uri",
      "preprocessingConfig",
      "securityRules",
      "inputStreamProperty",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Input.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Input.Tier.self, forKey: .tier) {
      self.tier = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    self.preprocessingConfig = try container.decodeIfPresent(
      PreprocessingConfig.self, forKey: .preprocessingConfig)
    self.securityRules = try container.decodeIfPresent(
      Input.SecurityRule.self, forKey: .securityRules)
    self.inputStreamProperty = try container.decodeIfPresent(
      InputStreamProperty.self, forKey: .inputStreamProperty)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.tier, forKey: .tier)
    try container.encode(self.uri, forKey: .uri)
    try container.encodeIfPresent(self.preprocessingConfig, forKey: .preprocessingConfig)
    try container.encodeIfPresent(self.securityRules, forKey: .securityRules)
    try container.encodeIfPresent(self.inputStreamProperty, forKey: .inputStreamProperty)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Security rules for access control. Each field represents one security rule.
  /// Only when the source of the input stream satisfies all the fields, this
  /// input stream can be accepted.
  public struct SecurityRule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// At least one ip range must match unless none specified. The IP range is
    /// defined by CIDR block: for example, `192.0.1.0/24` for a range and
    /// `192.0.1.0/32` for a single IP address.
    public var ipRanges: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SecurityRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SecurityRule().with { $0.ipRanges = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ipRanges = CodingKeys(stringValue: "ipRanges")

      static let _knownKeys: Set<Swift.String> = [
        "ipRanges"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipRanges) {
        self.ipRanges = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ipRanges, forKey: .ipRanges)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.Input.SecurityRule"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of the input.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Sendable {
    /// Input type is not specified.
    case unspecified
    /// Input will take an rtmp input stream.
    case rtmpPush
    /// Input will take an srt (Secure Reliable Transport) input stream.
    case srtPush
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .rtmpPush: return 1
      case .srtPush: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .rtmpPush: return "RTMP_PUSH"
      case .srtPush: return "SRT_PUSH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "RTMP_PUSH": self = .rtmpPush
      case "SRT_PUSH": self = .srtPush
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .rtmpPush
      case 2: self = .srtPush
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .rtmpPush: return try container.encode("RTMP_PUSH")
      case .srtPush: return try container.encode("SRT_PUSH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Tier of the input specification.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Tier: Codable, Equatable, Sendable {
    /// Tier is not specified.
    case unspecified
    /// Resolution < 1280x720. Bitrate <= 6 Mbps. FPS <= 60.
    case sd
    /// Resolution <= 1920x1080. Bitrate <= 25 Mbps. FPS <= 60.
    case hd
    /// Resolution <= 4096x2160. Bitrate <= 50 Mbps. FPS <= 60.
    case uhd
    /// Resolution <= 1280x720. Bitrate <= 6 Mbps. FPS <= 60. H265 codec.
    case sdH265
    /// Resolution <= 1920x1080. Bitrate <= 25 Mbps. FPS <= 60. H265 codec.
    case hdH265
    /// Resolution <= 4096x2160. Bitrate <= 50 Mbps. FPS <= 60. H265 codec.
    case uhdH265
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .sd: return 1
      case .hd: return 2
      case .uhd: return 3
      case .sdH265: return 4
      case .hdH265: return 5
      case .uhdH265: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TIER_UNSPECIFIED"
      case .sd: return "SD"
      case .hd: return "HD"
      case .uhd: return "UHD"
      case .sdH265: return "SD_H265"
      case .hdH265: return "HD_H265"
      case .uhdH265: return "UHD_H265"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Tier/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TIER_UNSPECIFIED": self = .unspecified
      case "SD": self = .sd
      case "HD": self = .hd
      case "UHD": self = .uhd
      case "SD_H265": self = .sdH265
      case "HD_H265": self = .hdH265
      case "UHD_H265": self = .uhdH265
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Tier/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .sd
      case 2: self = .hd
      case 3: self = .uhd
      case 4: self = .sdH265
      case 5: self = .hdH265
      case 6: self = .uhdH265
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TIER_UNSPECIFIED")
      case .sd: return try container.encode("SD")
      case .hd: return try container.encode("HD")
      case .uhd: return try container.encode("UHD")
      case .sdH265: return try container.encode("SD_H265")
      case .hdH265: return try container.encode("HD_H265")
      case .uhdH265: return try container.encode("UHD_H265")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Input"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
