// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration for the input sources of a channel.
public struct InputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Input switch mode. Default mode is `FAILOVER_PREFER_PRIMARY`.
  public var inputSwitchMode: InputConfig.InputSwitchMode = InputConfig.InputSwitchMode()

  /// Initialize a new instance of `InputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InputConfig().with { $0.inputSwitchMode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Input switch mode.
  public enum InputSwitchMode: Codable, Equatable, Sendable {
    /// The input switch mode is not specified.
    case unspecified
    /// Automatic failover is enabled. The primary input stream is always
    /// preferred over its backup input streams configured using the
    /// [AutomaticFailover][google.cloud.video.livestream.v1.InputAttachment.AutomaticFailover]
    /// field.
    ///
    /// [google.cloud.video.livestream.v1.InputAttachment.AutomaticFailover]: <doc:InputAttachment/AutomaticFailover>
    case failoverPreferPrimary
    /// Automatic failover is disabled. You must use the
    /// [inputSwitch][google.cloud.video.livestream.v1.Event.input_switch] event
    /// to switch the active input source for the channel to stream from. When
    /// this mode is chosen, the
    /// [AutomaticFailover][google.cloud.video.livestream.v1.InputAttachment.AutomaticFailover]
    /// field is ignored.
    ///
    /// [google.cloud.video.livestream.v1.Event.input_switch]: <doc:Event/OneOf_Task/inputSwitch(_:)>
    /// [google.cloud.video.livestream.v1.InputAttachment.AutomaticFailover]: <doc:InputAttachment/AutomaticFailover>
    case manual
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .failoverPreferPrimary: return 1
      case .manual: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INPUT_SWITCH_MODE_UNSPECIFIED"
      case .failoverPreferPrimary: return "FAILOVER_PREFER_PRIMARY"
      case .manual: return "MANUAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InputSwitchMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INPUT_SWITCH_MODE_UNSPECIFIED": self = .unspecified
      case "FAILOVER_PREFER_PRIMARY": self = .failoverPreferPrimary
      case "MANUAL": self = .manual
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InputSwitchMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .failoverPreferPrimary
      case 3: self = .manual
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .failoverPreferPrimary: return try container.encode(1)
      case .manual: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.InputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
