// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Properties of the input stream.
public struct InputStreamProperty: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time that the current input stream is accepted and the connection is
  /// established.
  public var lastEstablishTime: GoogleWKT.Timestamp? = nil

  /// Properties of the video streams.
  public var videoStreams: [VideoStreamProperty] = []

  /// Properties of the audio streams.
  public var audioStreams: [AudioStreamProperty] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InputStreamProperty`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InputStreamProperty().with { $0.lastEstablishTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let lastEstablishTime = CodingKeys(stringValue: "lastEstablishTime")
    static let videoStreams = CodingKeys(stringValue: "videoStreams")
    static let audioStreams = CodingKeys(stringValue: "audioStreams")

    static let _knownKeys: Set<Swift.String> = [
      "lastEstablishTime",
      "videoStreams",
      "audioStreams",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.lastEstablishTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastEstablishTime)
    if let value = try container.decodeIfPresent([VideoStreamProperty].self, forKey: .videoStreams)
    {
      self.videoStreams = value
    }
    if let value = try container.decodeIfPresent([AudioStreamProperty].self, forKey: .audioStreams)
    {
      self.audioStreams = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.lastEstablishTime, forKey: .lastEstablishTime)
    try container.encode(self.videoStreams, forKey: .videoStreams)
    try container.encode(self.audioStreams, forKey: .audioStreams)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.InputStreamProperty"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
