// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for "LivestreamService.ListEvents".
public struct ListEventsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent channel for the resource, in the form of:
  /// `projects/{project}/locations/{location}/channels/{channelId}`.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of items to return. If unspecified, server
  /// will pick an appropriate default. Server may return fewer items than
  /// requested. A caller should only rely on response's
  /// [next_page_token][google.cloud.video.livestream.v1.ListEventsResponse.next_page_token]
  /// to determine if there are more items left to be queried.
  ///
  /// [google.cloud.video.livestream.v1.ListEventsResponse.next_page_token]: <doc:ListEventsResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The next_page_token value returned from a previous List request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// The filter to apply to list results.
  public var filter: Swift.String = Swift.String()

  /// Specifies the ordering of results following syntax at
  /// https://cloud.google.com/apis/design/design_patterns#sorting_order.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEventsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.ListEventsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
