// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class LivestreamServiceLogging: LivestreamServiceStub {
    let inner: any LivestreamServiceStub
    let logger: Logger

    public init(_ inner: any LivestreamServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-video-livestream-v1"
      logger[metadataKey: "gcp.client.service"] = "livestream"
      logger[metadataKey: "gcp.experimental.swift.client"] = "LivestreamService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createChannel(
      request: CreateChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createChannel",
        action: {
          (r: CreateChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createChannel(request: r, options: o)
        })
    }

    public func listChannels(
      request: ListChannelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listChannels",
        action: {
          (r: ListChannelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListChannelsResponse
          in
          return try await self.inner.listChannels(request: r, options: o)
        })
    }

    public func getChannel(
      request: GetChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Channel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getChannel",
        action: {
          (r: GetChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Channel
          in
          return try await self.inner.getChannel(request: r, options: o)
        })
    }

    public func deleteChannel(
      request: DeleteChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteChannel",
        action: {
          (r: DeleteChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteChannel(request: r, options: o)
        })
    }

    public func updateChannel(
      request: UpdateChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateChannel",
        action: {
          (r: UpdateChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateChannel(request: r, options: o)
        })
    }

    public func startChannel(
      request: StartChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "startChannel",
        action: {
          (r: StartChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startChannel(request: r, options: o)
        })
    }

    public func stopChannel(
      request: StopChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "stopChannel",
        action: {
          (r: StopChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopChannel(request: r, options: o)
        })
    }

    public func startDistribution(
      request: StartDistributionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "startDistribution",
        action: {
          (r: StartDistributionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startDistribution(request: r, options: o)
        })
    }

    public func stopDistribution(
      request: StopDistributionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "stopDistribution",
        action: {
          (r: StopDistributionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopDistribution(request: r, options: o)
        })
    }

    public func createInput(
      request: CreateInputRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createInput",
        action: {
          (r: CreateInputRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInput(request: r, options: o)
        })
    }

    public func listInputs(
      request: ListInputsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListInputsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInputs",
        action: {
          (r: ListInputsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListInputsResponse
          in
          return try await self.inner.listInputs(request: r, options: o)
        })
    }

    public func getInput(
      request: GetInputRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Input {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInput",
        action: {
          (r: GetInputRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Input
          in
          return try await self.inner.getInput(request: r, options: o)
        })
    }

    public func deleteInput(
      request: DeleteInputRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteInput",
        action: {
          (r: DeleteInputRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInput(request: r, options: o)
        })
    }

    public func updateInput(
      request: UpdateInputRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateInput",
        action: {
          (r: UpdateInputRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInput(request: r, options: o)
        })
    }

    public func previewInput(
      request: PreviewInputRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.PreviewInputResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "previewInput",
        action: {
          (r: PreviewInputRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.PreviewInputResponse
          in
          return try await self.inner.previewInput(request: r, options: o)
        })
    }

    public func createEvent(
      request: CreateEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Event {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEvent",
        action: {
          (r: CreateEventRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Event
          in
          return try await self.inner.createEvent(request: r, options: o)
        })
    }

    public func listEvents(
      request: ListEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEvents",
        action: {
          (r: ListEventsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListEventsResponse
          in
          return try await self.inner.listEvents(request: r, options: o)
        })
    }

    public func getEvent(
      request: GetEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Event {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEvent",
        action: {
          (r: GetEventRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Event
          in
          return try await self.inner.getEvent(request: r, options: o)
        })
    }

    public func deleteEvent(
      request: DeleteEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEvent",
        action: { (r: DeleteEventRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteEvent(request: r, options: o)
        })
    }

    public func listClips(
      request: ListClipsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListClipsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listClips",
        action: {
          (r: ListClipsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListClipsResponse
          in
          return try await self.inner.listClips(request: r, options: o)
        })
    }

    public func getClip(
      request: GetClipRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Clip {
      try await self._intercept(
        request: request,
        options: options,
        name: "getClip",
        action: {
          (r: GetClipRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Clip
          in
          return try await self.inner.getClip(request: r, options: o)
        })
    }

    public func createClip(
      request: CreateClipRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createClip",
        action: {
          (r: CreateClipRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createClip(request: r, options: o)
        })
    }

    public func deleteClip(
      request: DeleteClipRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteClip",
        action: {
          (r: DeleteClipRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteClip(request: r, options: o)
        })
    }

    public func createDvrSession(
      request: CreateDvrSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDvrSession",
        action: {
          (r: CreateDvrSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDvrSession(request: r, options: o)
        })
    }

    public func listDvrSessions(
      request: ListDvrSessionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListDvrSessionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDvrSessions",
        action: {
          (r: ListDvrSessionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListDvrSessionsResponse
          in
          return try await self.inner.listDvrSessions(request: r, options: o)
        })
    }

    public func getDvrSession(
      request: GetDvrSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.DvrSession {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDvrSession",
        action: {
          (r: GetDvrSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.DvrSession
          in
          return try await self.inner.getDvrSession(request: r, options: o)
        })
    }

    public func deleteDvrSession(
      request: DeleteDvrSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDvrSession",
        action: {
          (r: DeleteDvrSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDvrSession(request: r, options: o)
        })
    }

    public func updateDvrSession(
      request: UpdateDvrSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDvrSession",
        action: {
          (r: UpdateDvrSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDvrSession(request: r, options: o)
        })
    }

    public func createAsset(
      request: CreateAssetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAsset",
        action: {
          (r: CreateAssetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAsset(request: r, options: o)
        })
    }

    public func deleteAsset(
      request: DeleteAssetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAsset",
        action: {
          (r: DeleteAssetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAsset(request: r, options: o)
        })
    }

    public func getAsset(
      request: GetAssetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Asset {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAsset",
        action: {
          (r: GetAssetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Asset
          in
          return try await self.inner.getAsset(request: r, options: o)
        })
    }

    public func listAssets(
      request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAssets",
        action: {
          (r: ListAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListAssetsResponse
          in
          return try await self.inner.listAssets(request: r, options: o)
        })
    }

    public func getPool(
      request: GetPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Pool {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPool",
        action: {
          (r: GetPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Pool
          in
          return try await self.inner.getPool(request: r, options: o)
        })
    }

    public func updatePool(
      request: UpdatePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePool",
        action: {
          (r: UpdatePoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePool(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
