// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol LivestreamServiceStub: Sendable {
    func createChannel(
      request: CreateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listChannels(
      request: ListChannelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListChannelsResponse

    func getChannel(
      request: GetChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Channel

    func deleteChannel(
      request: DeleteChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateChannel(
      request: UpdateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func startChannel(
      request: StartChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func stopChannel(
      request: StopChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func startDistribution(
      request: StartDistributionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func stopDistribution(
      request: StopDistributionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createInput(
      request: CreateInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listInputs(
      request: ListInputsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListInputsResponse

    func getInput(
      request: GetInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Input

    func deleteInput(
      request: DeleteInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateInput(
      request: UpdateInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func previewInput(
      request: PreviewInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.PreviewInputResponse

    func createEvent(
      request: CreateEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Event

    func listEvents(
      request: ListEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListEventsResponse

    func getEvent(
      request: GetEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Event

    func deleteEvent(
      request: DeleteEventRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listClips(
      request: ListClipsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListClipsResponse

    func getClip(
      request: GetClipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Clip

    func createClip(
      request: CreateClipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteClip(
      request: DeleteClipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createDvrSession(
      request: CreateDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDvrSessions(
      request: ListDvrSessionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListDvrSessionsResponse

    func getDvrSession(
      request: GetDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.DvrSession

    func deleteDvrSession(
      request: DeleteDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDvrSession(
      request: UpdateDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createAsset(
      request: CreateAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAsset(
      request: DeleteAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getAsset(
      request: GetAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Asset

    func listAssets(
      request: ListAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListAssetsResponse

    func getPool(
      request: GetPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Pool

    func updatePool(
      request: UpdatePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
