// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class LivestreamServiceRetry: LivestreamServiceStub {
    let inner: any LivestreamServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any LivestreamServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createChannel(
      request: CreateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createChannel(request: r, options: o)
        })
    }

    public func listChannels(
      request: ListChannelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListChannelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListChannelsResponse
          in
          return try await self.inner.listChannels(request: r, options: o)
        })
    }

    public func getChannel(
      request: GetChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Channel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Channel
          in
          return try await self.inner.getChannel(request: r, options: o)
        })
    }

    public func deleteChannel(
      request: DeleteChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteChannel(request: r, options: o)
        })
    }

    public func updateChannel(
      request: UpdateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateChannel(request: r, options: o)
        })
    }

    public func startChannel(
      request: StartChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startChannel(request: r, options: o)
        })
    }

    public func stopChannel(
      request: StopChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopChannel(request: r, options: o)
        })
    }

    public func startDistribution(
      request: StartDistributionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartDistributionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startDistribution(request: r, options: o)
        })
    }

    public func stopDistribution(
      request: StopDistributionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopDistributionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopDistribution(request: r, options: o)
        })
    }

    public func createInput(
      request: CreateInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInput(request: r, options: o)
        })
    }

    public func listInputs(
      request: ListInputsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListInputsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInputsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListInputsResponse
          in
          return try await self.inner.listInputs(request: r, options: o)
        })
    }

    public func getInput(
      request: GetInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Input {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Input
          in
          return try await self.inner.getInput(request: r, options: o)
        })
    }

    public func deleteInput(
      request: DeleteInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInput(request: r, options: o)
        })
    }

    public func updateInput(
      request: UpdateInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInput(request: r, options: o)
        })
    }

    public func previewInput(
      request: PreviewInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.PreviewInputResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PreviewInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.PreviewInputResponse
          in
          return try await self.inner.previewInput(request: r, options: o)
        })
    }

    public func createEvent(
      request: CreateEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Event {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Event
          in
          return try await self.inner.createEvent(request: r, options: o)
        })
    }

    public func listEvents(
      request: ListEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEventsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListEventsResponse
          in
          return try await self.inner.listEvents(request: r, options: o)
        })
    }

    public func getEvent(
      request: GetEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Event {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Event
          in
          return try await self.inner.getEvent(request: r, options: o)
        })
    }

    public func deleteEvent(
      request: DeleteEventRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteEventRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteEvent(request: r, options: o)
        })
    }

    public func listClips(
      request: ListClipsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListClipsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListClipsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListClipsResponse
          in
          return try await self.inner.listClips(request: r, options: o)
        })
    }

    public func getClip(
      request: GetClipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Clip {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetClipRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Clip
          in
          return try await self.inner.getClip(request: r, options: o)
        })
    }

    public func createClip(
      request: CreateClipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateClipRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createClip(request: r, options: o)
        })
    }

    public func deleteClip(
      request: DeleteClipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteClipRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteClip(request: r, options: o)
        })
    }

    public func createDvrSession(
      request: CreateDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDvrSessionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDvrSession(request: r, options: o)
        })
    }

    public func listDvrSessions(
      request: ListDvrSessionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListDvrSessionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDvrSessionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListDvrSessionsResponse
          in
          return try await self.inner.listDvrSessions(request: r, options: o)
        })
    }

    public func getDvrSession(
      request: GetDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.DvrSession {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDvrSessionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.DvrSession
          in
          return try await self.inner.getDvrSession(request: r, options: o)
        })
    }

    public func deleteDvrSession(
      request: DeleteDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDvrSessionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDvrSession(request: r, options: o)
        })
    }

    public func updateDvrSession(
      request: UpdateDvrSessionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDvrSessionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDvrSession(request: r, options: o)
        })
    }

    public func createAsset(
      request: CreateAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAssetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAsset(request: r, options: o)
        })
    }

    public func deleteAsset(
      request: DeleteAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAssetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAsset(request: r, options: o)
        })
    }

    public func getAsset(
      request: GetAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Asset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAssetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Asset
          in
          return try await self.inner.getAsset(request: r, options: o)
        })
    }

    public func listAssets(
      request: ListAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.ListAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAssetsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.ListAssetsResponse
          in
          return try await self.inner.listAssets(request: r, options: o)
        })
    }

    public func getPool(
      request: GetPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoLiveStreamV1.Pool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoLiveStreamV1.Pool
          in
          return try await self.inner.getPool(request: r, options: o)
        })
    }

    public func updatePool(
      request: UpdatePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePool(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
