// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Manifest configuration.
public struct Manifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the generated file. The default is `manifest` with the
  /// extension suffix corresponding to the `Manifest`
  /// [type][google.cloud.video.livestream.v1.Manifest.type]. If multiple
  /// manifests are added to the channel, each must have a unique file name.
  ///
  /// [google.cloud.video.livestream.v1.Manifest.type]: <doc:Manifest/type>
  public var fileName: Swift.String = Swift.String()

  /// Required. Type of the manifest, can be `HLS` or `DASH`.
  public var type: Manifest.ManifestType = Manifest.ManifestType()

  /// Required. List of `MuxStream`
  /// [key][google.cloud.video.livestream.v1.MuxStream.key]s that should appear
  /// in this manifest.
  ///
  /// - For HLS, either `fmp4` or `ts` mux streams can be specified but not
  /// mixed.
  /// - For DASH, only `fmp4` mux streams can be specified.
  ///
  /// [google.cloud.video.livestream.v1.MuxStream.key]: <doc:MuxStream/key>
  public var muxStreams: [Swift.String] = []

  /// Maximum number of segments that this manifest holds. Once the manifest
  /// reaches this maximum number of segments, whenever a new segment is added to
  /// the manifest, the oldest segment will be removed from the manifest.
  /// The minimum value is 3 and the default value is 5.
  public var maxSegmentCount: Swift.Int32 = Swift.Int32()

  /// How long to keep a segment on the output Google Cloud Storage bucket after
  /// it is removed from the manifest. This field should be large enough to cover
  /// the manifest propagation delay. Otherwise, a player could receive 404
  /// errors while accessing segments which are listed in the manifest that the
  /// player has, but were already deleted from the output Google Cloud Storage
  /// bucket. Default value is `60s`.
  ///
  /// If both segment_keep_duration and
  /// [RetentionConfig.retention_window_duration][google.cloud.video.livestream.v1.RetentionConfig.retention_window_duration]
  /// are set,
  /// [RetentionConfig.retention_window_duration][google.cloud.video.livestream.v1.RetentionConfig.retention_window_duration]
  /// is used and segment_keep_duration is ignored.
  ///
  /// [google.cloud.video.livestream.v1.RetentionConfig.retention_window_duration]: <doc:RetentionConfig/retentionWindowDuration>
  public var segmentKeepDuration: GoogleCloudWkt.Duration? = nil

  /// Whether to use the timecode, as specified in timecode config, when setting:
  ///
  /// - `availabilityStartTime` attribute in DASH manifests.
  /// - `#EXT-X-PROGRAM-DATE-TIME` tag in HLS manifests.
  ///
  /// If false, ignore the input timecode and use the time from system clock
  /// when the manifest is first generated. This is the default behavior.
  public var useTimecodeAsTimeline: Swift.Bool = Swift.Bool()

  /// Optional. A unique key for this manifest.
  public var key: Swift.String = Swift.String()

  /// Initialize a new instance of `Manifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Manifest().with { $0.fileName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The manifest type can be either `HLS` or `DASH`.
  public enum ManifestType: Codable, Equatable, Sendable {
    /// The manifest type is not specified.
    case unspecified
    /// Create an `HLS` manifest. The corresponding file extension is `.m3u8`.
    case hls
    /// Create a `DASH` manifest. The corresponding file extension is `.mpd`.
    case dash
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hls: return 1
      case .dash: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MANIFEST_TYPE_UNSPECIFIED"
      case .hls: return "HLS"
      case .dash: return "DASH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ManifestType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MANIFEST_TYPE_UNSPECIFIED": self = .unspecified
      case "HLS": self = .hls
      case "DASH": self = .dash
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ManifestType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hls
      case 2: self = .dash
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .hls: return try container.encode(1)
      case .dash: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.Manifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
