// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Multiplexing settings for output stream.
public struct MuxStream: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique key for this multiplexed stream. The key must be 1-63
  /// characters in length. The key must begin and end with a letter (regardless
  /// of case) or a number, but can contain dashes or underscores in between.
  public var key: Swift.String = Swift.String()

  /// The container format. The default is `fmp4`.
  ///
  /// Supported container formats:
  ///
  /// - `fmp4` - the corresponding file extension is `.m4s`
  /// - `ts` - the corresponding file extension is `.ts`
  public var container: Swift.String = Swift.String()

  /// List of `ElementaryStream`
  /// [key][google.cloud.video.livestream.v1.ElementaryStream.key]s multiplexed
  /// in this stream.
  ///
  /// - For `fmp4` container, must contain either one video or one audio stream.
  /// - For `ts` container, must contain exactly one audio stream and up to one
  /// video stream.
  ///
  /// [google.cloud.video.livestream.v1.ElementaryStream.key]: <doc:ElementaryStream/key>
  public var elementaryStreams: [Swift.String] = []

  /// Segment settings for `fmp4` and `ts`.
  public var segmentSettings: SegmentSettings? = nil

  /// Identifier of the encryption configuration to use. If omitted, output
  /// will be unencrypted.
  public var encryptionId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MuxStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MuxStream().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let container = CodingKeys(stringValue: "container")
    static let elementaryStreams = CodingKeys(stringValue: "elementaryStreams")
    static let segmentSettings = CodingKeys(stringValue: "segmentSettings")
    static let encryptionId = CodingKeys(stringValue: "encryptionId")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "container",
      "elementaryStreams",
      "segmentSettings",
      "encryptionId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .container) {
      self.container = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .elementaryStreams) {
      self.elementaryStreams = value
    }
    self.segmentSettings = try container.decodeIfPresent(
      SegmentSettings.self, forKey: .segmentSettings)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .encryptionId) {
      self.encryptionId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.container, forKey: .container)
    try container.encode(self.elementaryStreams, forKey: .elementaryStreams)
    try container.encodeIfPresent(self.segmentSettings, forKey: .segmentSettings)
    try container.encode(self.encryptionId, forKey: .encryptionId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.MuxStream"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
