// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Preprocessing configurations.
public struct PreprocessingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Audio preprocessing configuration.
  public var audio: PreprocessingConfig.Audio? = nil

  /// Specify the video cropping configuration.
  public var crop: PreprocessingConfig.Crop? = nil

  /// Specify the video pad filter configuration.
  public var pad: PreprocessingConfig.Pad? = nil

  /// Initialize a new instance of `PreprocessingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PreprocessingConfig().with { $0.audio = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Audio preprocessing configuration.
  public struct Audio: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Specify audio loudness normalization in loudness units relative to full
    /// scale (LUFS). Enter a value between -24 and 0 according to the following:
    ///
    /// - -24 is the Advanced Television Systems Committee (ATSC A/85)
    /// - -23 is the EU R128 broadcast standard
    /// - -19 is the prior standard for online mono audio
    /// - -18 is the ReplayGain standard
    /// - -16 is the prior standard for stereo audio
    /// - -14 is the new online audio standard recommended by Spotify, as well as
    /// Amazon Echo
    /// - 0 disables normalization. The default is 0.
    public var lufs: Swift.Double = Swift.Double()

    /// Initialize a new instance of `Audio`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Audio().with { $0.lufs = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig.Audio"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Video cropping configuration for the input video. The cropped input video
  /// is scaled to match the output resolution.
  public struct Crop: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of pixels to crop from the top. The default is 0.
    public var topPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the bottom. The default is 0.
    public var bottomPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the left. The default is 0.
    public var leftPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the right. The default is 0.
    public var rightPixels: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Crop`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Crop().with { $0.topPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig.Crop"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Pad filter configuration for the input video. The padded input video
  /// is scaled after padding with black to match the output resolution.
  public struct Pad: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of pixels to add to the top. The default is 0.
    public var topPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the bottom. The default is 0.
    public var bottomPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the left. The default is 0.
    public var leftPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the right. The default is 0.
    public var rightPixels: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Pad`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Pad().with { $0.topPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig.Pad"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
