// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Preprocessing configurations.
public struct PreprocessingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Audio preprocessing configuration.
  public var audio: PreprocessingConfig.Audio? = nil

  /// Specify the video cropping configuration.
  public var crop: PreprocessingConfig.Crop? = nil

  /// Specify the video pad filter configuration.
  public var pad: PreprocessingConfig.Pad? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PreprocessingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PreprocessingConfig().with { $0.audio = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let audio = CodingKeys(stringValue: "audio")
    static let crop = CodingKeys(stringValue: "crop")
    static let pad = CodingKeys(stringValue: "pad")

    static let _knownKeys: Set<Swift.String> = [
      "audio",
      "crop",
      "pad",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.audio = try container.decodeIfPresent(PreprocessingConfig.Audio.self, forKey: .audio)
    self.crop = try container.decodeIfPresent(PreprocessingConfig.Crop.self, forKey: .crop)
    self.pad = try container.decodeIfPresent(PreprocessingConfig.Pad.self, forKey: .pad)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.audio, forKey: .audio)
    try container.encodeIfPresent(self.crop, forKey: .crop)
    try container.encodeIfPresent(self.pad, forKey: .pad)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Audio preprocessing configuration.
  public struct Audio: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Specify audio loudness normalization in loudness units relative to full
    /// scale (LUFS). Enter a value between -24 and 0 according to the following:
    ///
    /// - -24 is the Advanced Television Systems Committee (ATSC A/85)
    /// - -23 is the EU R128 broadcast standard
    /// - -19 is the prior standard for online mono audio
    /// - -18 is the ReplayGain standard
    /// - -16 is the prior standard for stereo audio
    /// - -14 is the new online audio standard recommended by Spotify, as well as
    /// Amazon Echo
    /// - 0 disables normalization. The default is 0.
    public var lufs: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Audio`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Audio().with { $0.lufs = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let lufs = CodingKeys(stringValue: "lufs")

      static let _knownKeys: Set<Swift.String> = [
        "lufs"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .lufs) {
        self.lufs = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.lufs, forKey: .lufs)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig.Audio"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Video cropping configuration for the input video. The cropped input video
  /// is scaled to match the output resolution.
  public struct Crop: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The number of pixels to crop from the top. The default is 0.
    public var topPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the bottom. The default is 0.
    public var bottomPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the left. The default is 0.
    public var leftPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to crop from the right. The default is 0.
    public var rightPixels: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Crop`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Crop().with { $0.topPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let topPixels = CodingKeys(stringValue: "topPixels")
      static let bottomPixels = CodingKeys(stringValue: "bottomPixels")
      static let leftPixels = CodingKeys(stringValue: "leftPixels")
      static let rightPixels = CodingKeys(stringValue: "rightPixels")

      static let _knownKeys: Set<Swift.String> = [
        "topPixels",
        "bottomPixels",
        "leftPixels",
        "rightPixels",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .topPixels) {
        self.topPixels = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .bottomPixels) {
        self.bottomPixels = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .leftPixels) {
        self.leftPixels = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rightPixels) {
        self.rightPixels = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.topPixels, forKey: .topPixels)
      try container.encode(self.bottomPixels, forKey: .bottomPixels)
      try container.encode(self.leftPixels, forKey: .leftPixels)
      try container.encode(self.rightPixels, forKey: .rightPixels)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig.Crop"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Pad filter configuration for the input video. The padded input video
  /// is scaled after padding with black to match the output resolution.
  public struct Pad: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The number of pixels to add to the top. The default is 0.
    public var topPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the bottom. The default is 0.
    public var bottomPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the left. The default is 0.
    public var leftPixels: Swift.Int32 = Swift.Int32()

    /// The number of pixels to add to the right. The default is 0.
    public var rightPixels: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Pad`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Pad().with { $0.topPixels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let topPixels = CodingKeys(stringValue: "topPixels")
      static let bottomPixels = CodingKeys(stringValue: "bottomPixels")
      static let leftPixels = CodingKeys(stringValue: "leftPixels")
      static let rightPixels = CodingKeys(stringValue: "rightPixels")

      static let _knownKeys: Set<Swift.String> = [
        "topPixels",
        "bottomPixels",
        "leftPixels",
        "rightPixels",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .topPixels) {
        self.topPixels = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .bottomPixels) {
        self.bottomPixels = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .leftPixels) {
        self.leftPixels = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rightPixels) {
        self.rightPixels = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.topPixels, forKey: .topPixels)
      try container.encode(self.bottomPixels, forKey: .bottomPixels)
      try container.encode(self.leftPixels, forKey: .leftPixels)
      try container.encode(self.rightPixels, forKey: .rightPixels)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig.Pad"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.PreprocessingConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
