// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configurations for an output endpoint using RTMP_PUSH as the streaming
/// protocol.
public struct RtmpPushOutputEndpoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The full URI of the remote RTMP server. For example:
  /// `rtmp://192.168.123.321/live/my-stream` or `rtmp://somedomain.com/someapp`.
  public var uri: Swift.String = Swift.String()

  /// Required. Stream key for RTMP protocol.
  public var streamKey: Swift.String = Swift.String()

  /// Initialize a new instance of `RtmpPushOutputEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RtmpPushOutputEndpoint().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.RtmpPushOutputEndpoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
