// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Sprite sheet configuration.
public struct SpriteSheet: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Format type. The default is `jpeg`.
  ///
  /// Supported formats:
  ///
  /// - `jpeg`
  public var format: Swift.String = Swift.String()

  /// Required. File name prefix for the generated sprite sheets. If multiple
  /// sprite sheets are added to the channel, each must have a unique file
  /// prefix.
  /// Each sprite sheet has an incremental 10-digit zero-padded suffix starting
  /// from 0 before the extension, such as `sprite_sheet0000000123.jpeg`.
  public var filePrefix: Swift.String = Swift.String()

  /// Required. The width of the sprite in pixels. Must be an even integer.
  public var spriteWidthPixels: Swift.Int32 = Swift.Int32()

  /// Required. The height of the sprite in pixels. Must be an even integer.
  public var spriteHeightPixels: Swift.Int32 = Swift.Int32()

  /// The maximum number of sprites per row in a sprite sheet. Valid range is
  /// [1, 10] and the default value is 1.
  public var columnCount: Swift.Int32 = Swift.Int32()

  /// The maximum number of rows per sprite sheet. When the sprite sheet is full,
  /// a new sprite sheet is created. Valid range is [1, 10] and the default value
  /// is 1.
  public var rowCount: Swift.Int32 = Swift.Int32()

  /// Create sprites at regular intervals. Valid range is [1 second, 1 hour] and
  /// the default value is `10s`.
  public var interval: GoogleCloudWKT.Duration? = nil

  /// The quality of the generated sprite sheet. Enter a value between 1
  /// and 100, where 1 is the lowest quality and 100 is the highest quality.
  /// The default is 100. A high quality value corresponds to a low image data
  /// compression ratio.
  public var quality: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SpriteSheet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpriteSheet().with { $0.format = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let format = CodingKeys(stringValue: "format")
    static let filePrefix = CodingKeys(stringValue: "filePrefix")
    static let spriteWidthPixels = CodingKeys(stringValue: "spriteWidthPixels")
    static let spriteHeightPixels = CodingKeys(stringValue: "spriteHeightPixels")
    static let columnCount = CodingKeys(stringValue: "columnCount")
    static let rowCount = CodingKeys(stringValue: "rowCount")
    static let interval = CodingKeys(stringValue: "interval")
    static let quality = CodingKeys(stringValue: "quality")

    static let _knownKeys: Set<Swift.String> = [
      "format",
      "filePrefix",
      "spriteWidthPixels",
      "spriteHeightPixels",
      "columnCount",
      "rowCount",
      "interval",
      "quality",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .format) {
      self.format = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filePrefix) {
      self.filePrefix = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .spriteWidthPixels) {
      self.spriteWidthPixels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .spriteHeightPixels) {
      self.spriteHeightPixels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .columnCount) {
      self.columnCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rowCount) {
      self.rowCount = value
    }
    self.interval = try container.decodeIfPresent(GoogleCloudWKT.Duration.self, forKey: .interval)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .quality) {
      self.quality = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.format, forKey: .format)
    try container.encode(self.filePrefix, forKey: .filePrefix)
    try container.encode(self.spriteWidthPixels, forKey: .spriteWidthPixels)
    try container.encode(self.spriteHeightPixels, forKey: .spriteHeightPixels)
    try container.encode(self.columnCount, forKey: .columnCount)
    try container.encode(self.rowCount, forKey: .rowCount)
    try container.encodeIfPresent(self.interval, forKey: .interval)
    try container.encode(self.quality, forKey: .quality)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.SpriteSheet"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
