// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configurations for an output endpoint using SRT_PUSH as the streaming
/// protocol.
public struct SrtPushOutputEndpoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The full URI of the remote SRT server.
  public var uri: Swift.String = Swift.String()

  /// Defines where SRT encryption passphrase are stored.
  public var passphraseSource: OneOf_PassphraseSource? = nil

  /// Initialize a new instance of `SrtPushOutputEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SrtPushOutputEndpoint().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case uri = "uri"
    case passphraseSecretVersion = "passphraseSecretVersion"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.uri = try container.decode(Swift.String.self, forKey: .uri)

    var passphraseSource: OneOf_PassphraseSource? = nil
    let passphraseSourceCheckAndSet = {
      if passphraseSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'passphraseSource'"))
      }
      passphraseSource = $0
    }
    if let passphraseSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .passphraseSecretVersion)
    {
      try passphraseSourceCheckAndSet(.passphraseSecretVersion(passphraseSecretVersion))
    }
    self.passphraseSource = passphraseSource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)

    if let choice = self.passphraseSource {
      switch choice {
      case .passphraseSecretVersion(let value):
        try container.encode(value, forKey: .passphraseSecretVersion)
      }
    }
  }

  /// Defines where SRT encryption passphrase are stored.
  public enum OneOf_PassphraseSource: Codable, Equatable, Sendable {
    /// The name of the Secret Version containing the SRT encryption passphrase,
    /// which is stored in Google Secret Manager. It should be in the format of
    /// `projects/{project}/secrets/{secret_id}/versions/{version_number}`.
    case passphraseSecretVersion(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.SrtPushOutputEndpoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
