// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for the static overlay.
public struct StaticOverlay: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Asset to use for the overlaid image.
  /// The asset must be represented in the form of:
  /// `projects/{project}/locations/{location}/assets/{assetId}`.
  /// The asset's resource type must be image.
  public var asset: Swift.String = Swift.String()

  /// Optional. Normalized image resolution, based on output video resolution.
  /// Valid values are [0.0, 1.0]. To respect the original image aspect ratio,
  /// set either `w` or `h` to 0. To use the original image resolution, set both
  /// `w` and `h` to 0. The default is {0, 0}.
  public var resolution: NormalizedResolution? = nil

  /// Optional. Position of the image in terms of normalized coordinates of the
  /// upper-left corner of the image, based on output video resolution. For
  /// example, use the x and y coordinates {0, 0} to position the top-left corner
  /// of the overlay animation in the top-left corner of the output video.
  public var position: NormalizedCoordinate? = nil

  /// Optional. Target image opacity. Valid values are from `1.0` (solid,
  /// default) to `0.0` (transparent), exclusive. Set this to a value greater
  /// than `0.0`.
  public var opacity: Swift.Double = Swift.Double()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StaticOverlay`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StaticOverlay().with { $0.asset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let asset = CodingKeys(stringValue: "asset")
    static let resolution = CodingKeys(stringValue: "resolution")
    static let position = CodingKeys(stringValue: "position")
    static let opacity = CodingKeys(stringValue: "opacity")

    static let _knownKeys: Set<Swift.String> = [
      "asset",
      "resolution",
      "position",
      "opacity",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .asset) {
      self.asset = value
    }
    self.resolution = try container.decodeIfPresent(NormalizedResolution.self, forKey: .resolution)
    self.position = try container.decodeIfPresent(NormalizedCoordinate.self, forKey: .position)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .opacity) {
      self.opacity = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.asset, forKey: .asset)
    try container.encodeIfPresent(self.resolution, forKey: .resolution)
    try container.encodeIfPresent(self.position, forKey: .position)
    try container.encode(self.opacity, forKey: .opacity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.StaticOverlay"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
