// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration for the static overlay.
public struct StaticOverlay: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Asset to use for the overlaid image.
  /// The asset must be represented in the form of:
  /// `projects/{project}/locations/{location}/assets/{assetId}`.
  /// The asset's resource type must be image.
  public var asset: Swift.String = Swift.String()

  /// Optional. Normalized image resolution, based on output video resolution.
  /// Valid values are [0.0, 1.0]. To respect the original image aspect ratio,
  /// set either `w` or `h` to 0. To use the original image resolution, set both
  /// `w` and `h` to 0. The default is {0, 0}.
  public var resolution: NormalizedResolution? = nil

  /// Optional. Position of the image in terms of normalized coordinates of the
  /// upper-left corner of the image, based on output video resolution. For
  /// example, use the x and y coordinates {0, 0} to position the top-left corner
  /// of the overlay animation in the top-left corner of the output video.
  public var position: NormalizedCoordinate? = nil

  /// Optional. Target image opacity. Valid values are from `1.0` (solid,
  /// default) to `0.0` (transparent), exclusive. Set this to a value greater
  /// than `0.0`.
  public var opacity: Swift.Double = Swift.Double()

  /// Initialize a new instance of `StaticOverlay`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StaticOverlay().with { $0.asset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.StaticOverlay"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
