// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Encoding of a text stream. For example, closed captions or subtitles.
public struct TextStream: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The codec for this text stream.
  ///
  /// Supported text codecs:
  ///
  /// - `cea608`
  /// - `cea708`
  /// - `webvtt`
  public var codec: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code, such as `en-US` or `sr-Latn`. For more
  /// information, see
  /// https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
  public var languageCode: Swift.String = Swift.String()

  /// Optional. The name for this particular text stream that will be added to
  /// the HLS/DASH manifest.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The channel of the closed caption in the output stream.
  /// This field should only be set when textstream is used for partner
  /// distribution.
  /// Must be one of `CC1`, `CC2`, `CC3`, and `CC4`, if the
  /// [codec][google.cloud.video.livestream.v1.TextStream.codec] is `cea608`;
  /// Must be one between `SERVICE1` and `SERVICE63`, if the
  /// [codec][google.cloud.video.livestream.v1.TextStream.codec] is `cea708`.
  ///
  /// [google.cloud.video.livestream.v1.TextStream.codec]: <doc:TextStream/codec>
  public var outputCeaChannel: Swift.String = Swift.String()

  /// Optional. The mapping for the input streams and text tracks.
  public var mapping: [TextStream.TextMapping] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TextStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TextStream().with { $0.codec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let codec = CodingKeys(stringValue: "codec")
    static let languageCode = CodingKeys(stringValue: "languageCode")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let outputCeaChannel = CodingKeys(stringValue: "outputCeaChannel")
    static let mapping = CodingKeys(stringValue: "mapping")

    static let _knownKeys: Set<Swift.String> = [
      "codec",
      "languageCode",
      "displayName",
      "outputCeaChannel",
      "mapping",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .codec) {
      self.codec = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputCeaChannel) {
      self.outputCeaChannel = value
    }
    if let value = try container.decodeIfPresent([TextStream.TextMapping].self, forKey: .mapping) {
      self.mapping = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.codec, forKey: .codec)
    try container.encode(self.languageCode, forKey: .languageCode)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.outputCeaChannel, forKey: .outputCeaChannel)
    try container.encode(self.mapping, forKey: .mapping)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The mapping for the input streams and text tracks.
  public struct TextMapping: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The `Channel`
    /// [InputAttachment.key][google.cloud.video.livestream.v1.InputAttachment.key]
    /// that identifies the input that this text mapping applies to.
    ///
    /// [google.cloud.video.livestream.v1.InputAttachment.key]: <doc:InputAttachment/key>
    public var inputKey: Swift.String = Swift.String()

    /// Optional. The zero-based index of the track in the input stream.
    public var inputTrack: Swift.Int32 = Swift.Int32()

    /// Optional. The channel of the closed caption in the input stream.
    /// If this field is set, the output
    /// [codec][google.cloud.video.livestream.v1.TextStream.codec] must be
    /// `webvtt`. Must be one of `CC1`, `CC2`, `CC3`, and `CC4`, if the codec of
    /// the input closed caption is `cea608`; Must be one between `SERVICE1` and
    /// `SERVICE64`, if the codec of the input closed caption is `cea708`.
    ///
    /// [google.cloud.video.livestream.v1.TextStream.codec]: <doc:TextStream/codec>
    public var inputCeaChannel: Swift.String = Swift.String()

    /// Optional. The BCP-47 source language code, such as `en-US` or `sr-Latn`.
    /// If differ from the textStream's language code, enable translation. For
    /// more information on BCP-47 language codes, see
    /// https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
    public var fromLanguageCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TextMapping`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TextMapping().with { $0.inputKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputKey = CodingKeys(stringValue: "inputKey")
      static let inputTrack = CodingKeys(stringValue: "inputTrack")
      static let inputCeaChannel = CodingKeys(stringValue: "inputCeaChannel")
      static let fromLanguageCode = CodingKeys(stringValue: "fromLanguageCode")

      static let _knownKeys: Set<Swift.String> = [
        "inputKey",
        "inputTrack",
        "inputCeaChannel",
        "fromLanguageCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputKey) {
        self.inputKey = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .inputTrack) {
        self.inputTrack = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputCeaChannel) {
        self.inputCeaChannel = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fromLanguageCode) {
        self.fromLanguageCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inputKey, forKey: .inputKey)
      try container.encode(self.inputTrack, forKey: .inputTrack)
      try container.encode(self.inputCeaChannel, forKey: .inputCeaChannel)
      try container.encode(self.fromLanguageCode, forKey: .fromLanguageCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.livestream.v1.TextStream.TextMapping"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.TextStream"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
