// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Timecode configuration.
public struct TimecodeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The source of the timecode that will later be used in outputs/manifests.
  /// It determines the initial timecode/timestamp (first frame) of output
  /// streams.
  public var source: TimecodeConfig.TimecodeSource = TimecodeConfig.TimecodeSource()

  /// For EMBEDDED_TIMECODE source only.
  /// Used to interpret the embedded timecode (which contains only the time part
  /// and no date). We assume all inputs are live.
  public var timeOffset: OneOf_TimeOffset? = nil

  /// Initialize a new instance of `TimecodeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimecodeConfig().with { $0.source = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case source = "source"
    case utcOffset = "utcOffset"
    case timeZone = "timeZone"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.source = try container.decode(TimecodeConfig.TimecodeSource.self, forKey: .source)

    var timeOffset: OneOf_TimeOffset? = nil
    let timeOffsetCheckAndSet = {
      if timeOffset != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'timeOffset'"))
      }
      timeOffset = $0
    }
    if let utcOffset = try container.decodeIfPresent(
      GoogleCloudWKT.Duration?.self, forKey: .utcOffset)
    {
      try timeOffsetCheckAndSet(.utcOffset(utcOffset))
    }
    if let timeZone = try container.decodeIfPresent(GoogleType.TimeZone?.self, forKey: .timeZone) {
      try timeOffsetCheckAndSet(.timeZone(timeZone))
    }
    self.timeOffset = timeOffset
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.source, forKey: .source)

    if let choice = self.timeOffset {
      switch choice {
      case .utcOffset(let value):
        try container.encode(value, forKey: .utcOffset)
      case .timeZone(let value):
        try container.encode(value, forKey: .timeZone)
      }
    }
  }

  /// The source of timecode.
  public enum TimecodeSource: Codable, Equatable, Sendable {
    /// The timecode source is not specified.
    case unspecified
    /// Use input media timestamp.
    case mediaTimestamp
    /// Use input embedded timecode e.g. picture timing SEI message.
    case embeddedTimecode
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .mediaTimestamp: return 1
      case .embeddedTimecode: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TIMECODE_SOURCE_UNSPECIFIED"
      case .mediaTimestamp: return "MEDIA_TIMESTAMP"
      case .embeddedTimecode: return "EMBEDDED_TIMECODE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TimecodeSource/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TIMECODE_SOURCE_UNSPECIFIED": self = .unspecified
      case "MEDIA_TIMESTAMP": self = .mediaTimestamp
      case "EMBEDDED_TIMECODE": self = .embeddedTimecode
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TimecodeSource/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .mediaTimestamp
      case 2: self = .embeddedTimecode
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .mediaTimestamp: return try container.encode(1)
      case .embeddedTimecode: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// For EMBEDDED_TIMECODE source only.
  /// Used to interpret the embedded timecode (which contains only the time part
  /// and no date). We assume all inputs are live.
  public enum OneOf_TimeOffset: Codable, Equatable, Sendable {
    /// UTC offset. Must be whole seconds, between -18 hours and +18 hours.
    indirect case utcOffset(GoogleCloudWKT.Duration?)
    /// Time zone e.g. "America/Los_Angeles".
    indirect case timeZone(GoogleType.TimeZone?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.TimecodeConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
