// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Properties of the video format.
public struct VideoFormat: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Video codec used in this video stream.
  public var codec: Swift.String = Swift.String()

  /// The width of the video stream in pixels.
  public var widthPixels: Swift.Int32 = Swift.Int32()

  /// The height of the video stream in pixels.
  public var heightPixels: Swift.Int32 = Swift.Int32()

  /// The frame rate of the input video stream.
  public var frameRate: Swift.Double = Swift.Double()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoFormat`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoFormat().with { $0.codec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let codec = CodingKeys(stringValue: "codec")
    static let widthPixels = CodingKeys(stringValue: "widthPixels")
    static let heightPixels = CodingKeys(stringValue: "heightPixels")
    static let frameRate = CodingKeys(stringValue: "frameRate")

    static let _knownKeys: Set<Swift.String> = [
      "codec",
      "widthPixels",
      "heightPixels",
      "frameRate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .codec) {
      self.codec = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .widthPixels) {
      self.widthPixels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .heightPixels) {
      self.heightPixels = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .frameRate) {
      self.frameRate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.codec, forKey: .codec)
    try container.encode(self.widthPixels, forKey: .widthPixels)
    try container.encode(self.heightPixels, forKey: .heightPixels)
    try container.encode(self.frameRate, forKey: .frameRate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.livestream.v1.VideoFormat"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
